import type { Metadata } from "next";
import "./globals.css";
import SideNavbar from "./components/SideNavbar";
import Navbar from "./components/Navbar";


export const metadata: Metadata = {
  title: "Payment Delivery control system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="nord" className="">
      <body className="flex flex-col">
      <Navbar />

      <div className="w-full">
        {children}
      </div>
        
        </body>
    </html>
  );
}
