import type { Metadata } from "next";
import "./globals.css";
import SideNavbar from "./components/SideNavbar";
import Header from "./components/Header";


export const metadata: Metadata = {
  title: "Payment Delivery control system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="layout-main">
      <body>
      <SideNavbar />
      <div className="headerMainContainer">
        <Header />
        {children}
      </div>
        
        </body>
    </html>
  );
}
