import "./globals.css";
import Navbar from "./components/Navbar";


export const metadata = {
  title: "Payment Delivery control system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en" data-theme="nord" className="">
      <body className="flex flex-col ">
      <Navbar />

      <div className="w-full px-6">
        {children}
      </div>
        
        </body>
    </html>
  );
}
